### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by UriHerrera** [nomad-desktop/nx-software-center#1]
*It's still a work in progress*

![](http://i.imgur.com/4xu9baJ.png)
![](http://i.imgur.com/jk0V1Vy.png)
![](http://i.imgur.com/wABmqEX.png)
![](http://i.imgur.com/wfpONrZ.png)

So for the software center we have the following:

- 4 buttons that display 4 different views.
- A search bar.
- Hamburger menu to access the preferences.

The 4 views are:

1. **Start**: This is where the snaps are listed and managed (removed). The checkbox (an icon from emblems/22/emblem-default) at the top-right is an indicator for the snap that means it is installed and up-to-date. This status indicator changes when there's an update available (emblems/22/emblem-important). When a snap is removed (uninstalled) the item is not removed from this list but remains there as a mean of letting the user know what apps he has had installed before in case the user wishes to install them again, in this case the button changes from "Remove" to "Reinstall" and the checkbox icon disappears.
2. **Discover**: A categorized view of applications. Categories are displayed as parallax-styled banners. The backgrounds in these banners could be pulled from the internet to avoid storing them locally. On top of these are the name of the category and a button to view the applications inside that category. When the user enters on a category the apps ar elisted on an horizontal scrollable list and to "close" the listing there's a back button at the bottom right of the area that covers the banner.
3. **Newly Added/Recently Updated**:  Apps are listed vertically with the newly added apps at the top.
4. **Download Queue:** Only updates and downloads are listed here. Items are also sorted as sqaures however when an item is selected for update the item occupies the width of the window and moved to the top while the other items remain in a grid.

**Comment by azubieta** [comment]
@UriHerrera the Settings view is functional would you please check and make me a better design. Mine is quite ugly.

**Comment by azubieta** [comment]
I'm considering move the actions to a status bar, so when you select an item they will be shown just like this screenshot (it's still a mockup) 
![screenshot_20170128_151803](https://cloud.githubusercontent.com/assets/1138094/22399570/297d25b2-e56d-11e6-8a0f-a88e776202b9.png)

**Comment by UriHerrera** [comment]
@azubieta They would only show up when an item is selected right?.

**Comment by UriHerrera** [comment]
Preferences:

![](http://i.imgur.com/Dwj8lKR.png)

**Comment by azubieta** [comment]
I was thinking on keeping the status bar always visible and change the displayed actions according to the current view. When an action is triggered the user will be able to view the progress in the same area and the finish/error notifications will be shown there too.
 
I already uploaded the a functional version, please take a look at it.

Showing the status bar only when there is something selected, an operation running or a notification is also possible. Just let me know after checking it wish one  you prefer.

**Comment by UriHerrera** [comment]
> Showing the status bar only when there is something selected, an operation running or a notification is also possible. Just let me know after checking it wish one you prefer.

I'd say this is better. Also, whenever an action is performed we'd get a notification in the status panel rather than on the status bar.
