### ISSUE TITLE
Separate app to handle system updates 

### ISSUE THREAD

**Issue by UriHerrera** [nomad-desktop/nx-software-center#10]
Currently to perform system updates users have to use Konsole, while it isn't rocket science it'd be understandable that users wouldn't want to use it so since we have a software center it should handle system updates.

**Comment by azubieta** [comment]
I would not like to mix system with apps, instead I would recommend creating a separate app for system updates.

**Comment by UriHerrera** [comment]
There are these tools that are in the Ubuntu repos. I think these are to upgrade to a new Ubuntu release:
 
https://packages.ubuntu.com/zesty/ubuntu-core-upgrader
https://packages.ubuntu.com/artful/ubuntu-release-upgrader-qt
https://packages.ubuntu.com/artful/upgrade-system

While I think these are more specific to perform updates:
https://packages.ubuntu.com/artful/update-manager-core
https://packages.ubuntu.com/artful/update-manager

And here's the KDE version:
https://packages.ubuntu.com/artful/update-manager-kde

It doesn't seem to require Discover (unlike muon packages) however it depends on sip-py3api-11.2 which is a virtual package :/

**Comment by UriHerrera** [comment]
This si the GTK version:

Pop-up window:
![](https://i.imgur.com/9a2nYyM.png)

Expanded list of updates:
![](https://i.imgur.com/PRYBhO6.png)

Changelog visible:
![](https://i.imgur.com/dIvM816.png)

Asking the user for the password:
![](https://i.imgur.com/9mEUqH6.png)

Progress:
![](https://i.imgur.com/KNhzYYV.png)

How it's listed in XFCE's settings, same can be done in System Settings. Clicking the entry there launches the pop-up window.:
![](https://i.imgur.com/lVz4BuX.png)

**Comment by UriHerrera** [comment]
Moved to https://github.com/nomad-desktop/nx-software-updater/issues/1
