### ISSUE TITLE
Provide AppImage of nx-software-center

### ISSUE THREAD

**Issue by probonopd** [nomad-desktop/nx-software-center#11]
Since Snappy and AppImage are distribution-agnostic, it would probably be possible to make nx-software-center run on various distributions, hence increasing its reach significantly, especially in the testing stage.

Please consider to provide nx-software-center as an AppImage, so that people without nxos can try it out. It should be pretty straightforward to do by using https://github.com/probonopd/linuxdeployqt with Travis CI as shown in the examples on https://github.com/probonopd/linuxdeployqt#projects-using-linuxdeployqt.

Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed (except when handling snaps!)
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/) central directory of available AppImages

[Here is an overview](https://github.com/probonopd/AppImageKit/wiki/AppImages) of projects that are already distributing upstream-provided, official AppImages.

**Comment by llelectronics** [comment]
Yeah that would be helpful. 
We wanted to test it but failed compiling because of the libappimage depdency. 
Would be nice to also have an arm64 AppImage.

**Comment by star-buck** [comment]
How does AppImage handle listing+providing arm64 images over NXOS SC on an
aarch64 system?

**Comment by azubieta** [comment]
Right now, we get the appimages list from [appimagehub](https://appimage.github.io/feed.json) where there is no information of the available releases. Those are scraped from the install page indicated.
So there is no warranty currently that a given AppImage is available for a certain architecture.
This is something that we must discuss with the appimage team.

**Comment by probonopd** [comment]
As far as I can see, NX Software Center is currently only displaying `x86_64` software.

There are currently two ways to find out the architecture of an AppImage: checking that the file name/download URL contains `x86_64`; and/or downloading the first few bytes of it and check its magic bytes.

**Comment by probonopd** [comment]
@llelectronics 
> We wanted to test it but failed compiling because of the libappimage depdency.

I have started to make an AppImage on Travis CI here:
https://github.com/probonopd/nx-software-center/blob/patch-1/.travis.yml

But I am getting a compile error due to an unmet dependency on `<KIO/TransferJob>`. @azubieta had indicated that this dependency might eventually go away, which I'd consider a plus.

**Comment by azubieta** [comment]
Working on it. Now the kf5 dependency was removed.

**Comment by azubieta** [comment]
Now we have AppImage and continuous builds :smile: 
But I wasn't able to get the appimage generated from a tag pushed to the corresponding git release.
@probonopd any suggestions here ?

**Comment by probonopd** [comment]
Getting

```
QQmlApplicationEngine failed to load component
qrc:/main.qml:6 module "org.kde.plasma.components" is not installed
qrc:/main.qml:2 module "QtQuick.Controls" is not installed
qrc:/main.qml:5 module "org.kde.plasma.core" is not installed
qrc:/main.qml:3 module "QtQuick.Layouts" is not installed
qrc:/main.qml:1 module "QtQuick" is not installed
qrc:/main.qml:6 module "org.kde.plasma.components" is not installed
qrc:/main.qml:2 module "QtQuick.Controls" is not installed
qrc:/main.qml:5 module "org.kde.plasma.core" is not installed
qrc:/main.qml:3 module "QtQuick.Layouts" is not installed
qrc:/main.qml:1 module "QtQuick" is not installed
qrc:/main.qml:6 module "org.kde.plasma.components" is not installed
qrc:/main.qml:2 module "QtQuick.Controls" is not installed
qrc:/main.qml:5 module "org.kde.plasma.core" is not installed
qrc:/main.qml:3 module "QtQuick.Layouts" is not installed
qrc:/main.qml:1 module "QtQuick" is not installed
qrc:/main.qml:6 module "org.kde.plasma.components" is not installed
qrc:/main.qml:2 module "QtQuick.Controls" is not installed
qrc:/main.qml:5 module "org.kde.plasma.core" is not installed
qrc:/main.qml:3 module "QtQuick.Layouts" is not installed
qrc:/main.qml:1 module "QtQuick" is not installed
qrc:/main.qml:6 module "org.kde.plasma.components" is not installed
qrc:/main.qml:2 module "QtQuick.Controls" is not installed
qrc:/main.qml:5 module "org.kde.plasma.core" is not installed
qrc:/main.qml:3 module "QtQuick.Layouts" is not installed
qrc:/main.qml:1 module "QtQuick" is not installed
```

Need to use the `-qmldir=<path>` option of `linuxdeployqt` and point to the directory where the QML files are in the source.

**Comment by azubieta** [comment]
@probono new the qmldir option is set and the native qt qml plugins were included in the appimage but not the kf5 plugins (org.kde.plasma.components, org.kde.plasma.core, org.kde.plasma.extras). 
Should I fill you a bug linuxdeployqt?

**Comment by TheAssassin** [comment]
@azubieta linuxdeployqt doesn't have any special support for KDE and the KDE framework (yet).

**Comment by probonopd** [comment]
Maybe yo need to use `-qmldir=<path>` more than once to also point to the Kf5 ones?

**Comment by probonopd** [comment]
Is there a working AppImage for download somewhere?

**Comment by azubieta** [comment]
Not yet still struggling with Linuxdeployqt and Travis

**Comment by azubieta** [comment]
@probonopd Plase confirm if it's working as expected to close this issue.
https://transfer.sh/iAWb7/nx_software_center
Or check our releases page.

**Comment by probonopd** [comment]
Unfortunately it's still missing a dep:

```
me@host:~$ Downloads/nx_software_center 
QQmlApplicationEngine failed to load component
qrc:/main.qml:1 plugin cannot be loaded for module "QtQuick": Cannot load library /tmp/.mount_nx_sofLuJQCo/usr/qml/QtQuick.2/libqtquick2plugin.so: (libQt5Quick.so.5: cannot open shared object file: No such file or directory)
```

Did you copy in `QtQuick.2` manually or did `linuxdeployqt` do that?

**Comment by probonopd** [comment]
Actually `libQt5Quick.so.5` is bundled inside the AppImage but `libqtquick2plugin.so` is lacking the `rpath` to find it.

**Comment by probonopd** [comment]
I am getting somewhere when fixing this manually:

```
patchelf --set-rpath '$ORIGIN/../../lib/' squashfs-root/usr/qml/QtQuick.2/libqtquick2plugin.so
```

But hey, `linuxdeployqt` should normally do this automatically, so we need to find out why it doesn't.

**Comment by probonopd** [comment]
This is how it looks on Xubuntu 16.04:

![](https://user-images.githubusercontent.com/2480569/36060146-3e43a708-0e3b-11e8-8b44-16b8f040a65d.png)

Functionally it's working (can "install" and "uninstall" applications)

**Comment by star-buck** [comment]
Doesnt appimage use a field for appstream-id, so it could pull all those nice infos and screenshots from there?

**Comment by probonopd** [comment]
Sure. If the AppImage contains AppStream XML, then a subset of the information from it is included in https://appimage.github.io/feed.json. Let me know if something should be changed/added.

**Comment by azubieta** [comment]
@probonopd I forgot to include the plasma qml controls style. 
About the AppStream XML, right now almost any application in appimagehub has that nice info :(
It would be great to improve that.

**Comment by azubieta** [comment]
@probonopd @UriHerrera The nx-software-center ui is made as a pure desktop plasma app, so the theme is grabbed from plasma themes and the icons from the system icons. The idea was to achieve a total blend with the system in what respect to the GUI.
Now when we try to make our application portable this became an issue. The new target systems don't provide all the components that we require.
Options:
1- "Try" to bundle in the plasma theme resources
2- Use default qt quick components

**Comment by TheAssassin** [comment]
> 2- Use default qt quick components

Doesn't that introduce a significant amount of work? I'd expect you have to maintain quite a lot of code for that. Otherwise, I wouldn't care too much about a less-system-like look on non-Plasma desktops.

> 1- "Try" to bundle in the plasma theme resources

If you go for that option, please document the process in the AppImageKit wiki. We receive questions like "how can I bundle <stuff for platform XYZ>` occasionally, and being able to give them a link to a Wiki page helps both us and the person asking.

**Comment by azubieta** [comment]
@TheAssassin The second option actually reduces the maintenance efforts and the amount of dependencies. The drawback is that the application theme and the system theme will not match a 100%.
I'm attempting the first choice right now. But I can't tell how much flexible the plasma themes are.

**Comment by TheAssassin** [comment]
Do you intend to ship this application as an AppImage for Nitrux as well? If not, I'd go for the second version.

**Comment by azubieta** [comment]
Indeed we want, but we would not like it to be only limited to Nitrux. This is why we are making an appimage of it.

**Comment by TheAssassin** [comment]
Sure. My idea would have been to build it as a traditional package for Nitrux with support for the Plasma themes, and build an AppImage with a non-Plasma UI.

**Comment by geckolinux** [comment]
Hi I just tried the Software Center AppImage on openSUSE Tumbleweed, and I ran into the following error:

``````````````````
./Software_Center-e8bfbe1-x86_64.AppImage 
QQmlApplicationEngine failed to load component
qrc:/main.qml:1 plugin cannot be loaded for module "QtQuick": Cannot load library /tmp/.mount_SoftwaCMRxpI/usr/qml/QtQuick.2/libqtquick2plugin.so: (/usr/lib64/libQt5Quick.so.5: version `Qt_5_PRIVATE_API' not found (required by /tmp/.mount_SoftwaCMRxpI/usr/qml/QtQuick.2/libqtquick2plugin.so))

**Comment by TheAssassin** [comment]
It looks like the AppImage is loading Qt components from the system. That's actually not a good sign. Further investigation needed.

**Comment by azubieta** [comment]
The release [v2.1.1]( https://github.com/nomad-desktop/nx-software-center/releases/tag/v2.1.1 ) should work on Ubuntu Xenial and above. 

@geckolinux Mind to try that release.
@probonopd @TheAssassin I have been making some hacks to bundle the plasma qml components. But i would not recommend it as the way of packing plasma based apps. I think that we better wait until the new linuxdeployqt is ready.

**Comment by geckolinux** [comment]
Thanks for the fast fix. It does indeed launch now on openSUSE Tumbleweed. I'm not sure if it's rendering and working correctly. Here's a screenshot:

![screenshot from 2018-02-15 07-20-25](https://user-images.githubusercontent.com/2692138/36256396-c01457b2-1220-11e8-8152-909ca7686529.png)

The turquoise colored square in the top left corner looks like a button, but doesn't appear to do anything. When I attempt to install something, it does download a large file, and it changes the status button to "Remove", but I don't see any way to launch the application.

**Comment by azubieta** [comment]
Its not a rendering issue but the icons theme that is not being found
properly.

Remember that you must install appimaged altogueter with the software
center to make the downloaded apps available from you menu.

**Comment by probonopd** [comment]
It is now clocking in at a whopping 47.1 MB - I assume this is not optimized for size yet...

**Comment by probonopd** [comment]
Is there a way to launch an installed app from the Software Center?

**Comment by probonopd** [comment]
This is how it looks on Xubuntu 16.04 at the moment; functionally it is working:

![screenshot_2018-02-16_20-35-38](https://user-images.githubusercontent.com/2480569/36325722-a1df2de0-1350-11e8-8cb1-eb35c13cd495.png)

**Comment by TheAssassin** [comment]
> Is there a way to launch an installed app from the Software Center?

No, the app requires appimaged to run on the system. It "installs" the software into `~/bin`.

**Comment by probonopd** [comment]
I'd appreciate if there was a "Run" button (at least directly following the installation) - should be very easy to do. I assume most people want to run the app they just installed immediately.

**Comment by TheAssassin** [comment]
> I'd appreciate if there was a "Run" button

Something we could implement with the notifications suggested in https://github.com/AppImage/AppImageKit/issues/657.

**Comment by probonopd** [comment]
No, I mean the "Run" button should be right next to "Get".

**Comment by azubieta** [comment]
@probonopd did you try the latest [release 2.1.2](https://github.com/nomad-desktop/nx-software-center/releases/tag/v2.1.2)?

**Comment by probonopd** [comment]
Yes. The "Get" button turns into a "Remove" button, but I am missing the "Run" button.

**Comment by probonopd** [comment]
Also, a download progress indicator inside the app would be a great thing to have.

**Comment by azubieta** [comment]
Closing this issue, as there is a quite usable appimage.
If you find issues whit an specific distribution please open a new issue.

**Comment by probonopd** [comment]
Thank you. Very helpful.
