### ISSUE TITLE
Add support for OCS-Install

### ISSUE THREAD

**Issue by UriHerrera** [nomad-desktop/nx-software-center#12]
From [opendesktop.org](https://www.opendesktop.org)

> OCS-Install
> To install items via the "Install" button, you can either use OCS-URL (see below) or the OCS-Store:
> 
> https://www.linux-apps.com/p/1175480/.
> 
> OCS-Store works out-of-the-box with OCS, so clicking on any "OCS-Install" button will download, extracts and copy a file or archive to the appropriate theme location of most well-known Linux Distros and Desktop Environments.
>
> OCS-URL - Browser Protocol Extension
> OCS-URL allows easy distro-independent installation of themes, wallpapers, etc. under most desktop environments by simply clicking on the "Install" button. (Note: You can use the Opendesktop.org-App if you don't want to install this extra).
>
> Video Installation Guide
> Here is a video how to install ocs-url program: https://www.youtube.com/watch?v=R2qgkPrHutE
>
> 
> Installation Guide
> To install ocs-url program, get the package from here: https://www.linux-apps.com/p/1136805/
> 
> After ocs-url program is installed, you can click any "Install" button on openDesktop.org. Only supported filetypes have an "Install" button.
> 
> Browser Setup
> If you use Firefox, a program selection window opens the first time you click on an Install button: Choose "ocs-url" as custom URL handler and tick "remember the file association".
> 
> If you don't get the program selection window or you are using another browser, please set the ocs-url program as custom URL handler for ocs:// scheme in the browser's settings.

=====

ocs-url

https://github.com/opendesktop/ocs-url

An install helper program for items served on OpenCollaborationServices (OCS).

====

The case being that this is used to install AppImages, so when the user browses the OpenDesktop web store the download is done using the software center.

**Comment by probonopd** [comment]
> The case being that this is used to install AppImages

There is no need to "install" AppImages. If the optional `appimaged` daemon is running, then it is sufficient to drop them into one of the monitored directories as described on https://github.com/AppImage/AppImageKit#appimaged-usage

**Comment by UriHerrera** [comment]
I understand that, I mena install in the context of downloading the files to the folders that appimaged is monitoring.

**Comment by azubieta** [comment]
User tend to have their favorite download managers, also it would net be an simple task to implement all of its the functionalities properly.

Also from my point of view we should not force how the user downloads and appimage.
What we actually can do is to provide the means to verify that appimage (signature checking and other checks that we could implement), making it runnable (the default appimaged behavior of making all executable is a security risk) and integrating it to the system (user wide or system wide).

@probonopd any toughs about it? I'm thinking here in something like what Mac does when you download .dmg file.

**Comment by probonopd** [comment]
> @probonopd any toughs about it? I'm thinking here in something like what Mac does when you download .dmg file.

Exactly, that's what we should do. `appimaged` could check the signature and if it is trusted, set the executable bit. If not, then create a desktop file that runs the application through Firejail, without setting the executable bit. In fact, I had started to implement this some time ago at https://github.com/AppImage/AppImageKit/blob/80eb15473dbb9287f4eab4ef431cc1d0b658b958/src/shared.c#L489-L503 but the [signature checking stuff](https://github.com/AppImage/AppImageKit/blob/83b82870e1ab03e63178467376be378baca2922e/src/validate.c) is not tied in yet.

**Comment by star-buck** [comment]
2.1.2 version tested and works on Manjaro!
When downloading an AppImage, the directory created "bin" isnt hidden though, should be ".bin" I assume.

**Comment by probonopd** [comment]
On openSUSE, for example, they have had `$HOME/bin` since a very long time, and it's even on the `$PATH` by default.

**Comment by probonopd** [comment]
@star-buck in case you haven't seen it yet, https://www.youtube.com/watch?time_continue=1295&v=IzZxpg4GmRQ is worth watching ;-)

**Comment by azubieta** [comment]
@star-buck the idea was to allow "uninstall" appimages also posible by removing the file or "install".
That's why the bin isn't hidden.

**Comment by probonopd** [comment]
Also, it makes it easier for people to copy AppImages (e.g., to a USB stick or over the network), etc. - so I like it 👍

**Comment by star-buck** [comment]
Personally i think it looks total whacky and gives the impression of somehting is wrong... esepcially since people like their desktop "clean".
I would strongly name the folder then "AppImages" and not bin, esepcially if no other distro uses it so far and it gets forcibly created anyway, so the argument of "its already there" doesnt count.

**Comment by star-buck** [comment]
then simply add "AppImages" and ".AppImages"...
People used to "clean up" their windows machines inside all kind of accessible folders.
They removed important files from their root-directory, rendering it useless after restart.
If the install-dir is hidden, they dont care though.
If the install-sir should be accessible, name it "AppImages", as "bin" looks horribly wrong.
It also has an advertising effect, that any screenshot where to see "AppImages" you know people use it, whereas "bin" has people just wondering... think of the marketing aspect as people love to post screenshots everywhere and people start asking what this "AppImages" folder is for...

**Comment by probonopd** [comment]
Would you be fine with `$HOME/Applications` too? (I think we should not treat AppImages "specially", and "normal" people don't know what an AppImage is.)

**Comment by star-buck** [comment]
Applications is better than bin, sure, i just thought of the marketing...

**Comment by UriHerrera** [comment]
I think `$HOME/Applications ` works fine as it would be more "normal" for mainstream users (coming from Windows and Mac; that have used a mobile OS). They will be familiar with the term "Application".

**Comment by probonopd** [comment]
Added in https://github.com/AppImage/AppImageKit/commit/09dfd37b6115881800fd35489b413032942b9859

**Comment by azubieta** [comment]
Closing this, as the appimages only requires to be downloaded and this is best implemented by a download manager or web browser.
Furter desktop integration is performed by appimaged.

If you have any other idea reagarding this issue feel free to reopen it.
