### ISSUE TITLE
Notify of network errors.

### ISSUE THREAD

**Issue by luis-lavaire** [nomad-desktop/nx-software-center#15]
When an internet connection is unavailable, the user should be notified. ATM, when a connection is unavailable, a spinner turns endless, but no error is displayed.

**Comment by luis-lavaire** [comment]
I tried the app yesterday and got a message telling me I wasn't connected to any network. Is the issue fixed already @azubieta?

**Comment by azubieta** [comment]
Those messages are not the ones in the design. So no, this issue is still
valid

**Comment by luis-lavaire** [comment]
Oh, I see.

**Comment by azubieta** [comment]
Well I'm reviewing the designs right now and there is no one that matches this case so. So the issue could be closed @UriHerrera if you have any proposal on this please reopen it.
