### ISSUE TITLE
Software Center doesn't display apps

### ISSUE THREAD

**Issue by UriHerrera** [nomad-desktop/nx-software-center#16]
The software center is not displaying applications and simply shows a _no applications were found_ message.
![](https://i.imgur.com/QSwCLUg.png)

I have confirmed this bug is also present in the live session so it might not be a problem with the software center itself. 

Running it from the terminal only outputs this:

```
uri@600t:~$ nomad_software_center 
Both point size and pixel size set. Using pixel size.
Both point size and pixel size set. Using pixel size.
uri@600t:~$ 
````

**Comment by azubieta** [comment]
This will be fixed in the next release.

**Comment by wpostma** [comment]
This is happening to me too.  It was initially showing something, but on the second time I open the app it went into this bad state

**Comment by UriHerrera** [comment]
This has been fixed in the newest release.
