### ISSUE TITLE
Appstream

### ISSUE THREAD

**Issue by star-buck** [nomad-desktop/nx-software-center#24]
https://github.com/ximion/appstream
https://www.freedesktop.org/software/appstream/docs/

What I dont understand:
Is there already a centralized place where appstream information is submitted and stored?

As it mentiones such a thing here: https://en.wikipedia.org/wiki/AppStream
"...which aims at creating an unified software metadata database, and also a centralized [...] user-contributed content database".

**Comment by star-buck** [comment]
More info around Appstream listings:
https://medium.com/elementaryos/developer-tips-make-a-killer-appcenter-listing-ae74da4ecaec

**Comment by azubieta** [comment]
I'm [forwarding](https://github.com/ximion/appstream/issues/176) the question to the appstream maintainer. 
Being able to fecth that information would be great for this software center.

**Comment by azubieta** [comment]
In short: no there is no centralized place where Appstream information is submitted and stored. It's just the spec of how to serve it.
