### ISSUE TITLE
Change icons in the toolbar

### ISSUE THREAD

**Issue by UriHerrera** [nomad-desktop/nx-software-center#25]
Currently the icon used for the tasks view toolbar button is `appimage-store` however this icon is meant to be used for the [**Store** component](https://github.com/nomad-desktop/nx-software-center/issues/14) which currently is not ready yet. The correct icon to use for the tasks view where the download indicator and the download history are should be `document-download`.

**Comment by UriHerrera** [comment]
Actually noticed this too:  If we're considering the Store component as the view from where the user gets the AppImages using the icon `nx-software-center` would be wrong it should be `appimage-store`; so both icons currently used in the toolbar are the wrong icons.

**Comment by azubieta** [comment]
Something like this ??
![screenshot_20180312_180357](https://user-images.githubusercontent.com/1138094/37315512-be50d794-261f-11e8-8999-8fdfd28c364a.png)

**Comment by UriHerrera** [comment]
Yep.

**Comment by azubieta** [comment]
Merged at ecbe7e6
