### ISSUE TITLE
Appimage Network errors

### ISSUE THREAD

**Issue by silvernode** [nomad-desktop/nx-software-center#33]
```Error FODC0002 in https://www.appimagehub.com/ocs/v1/content/data?package_types=1&page=0: Error creating SSL context ()```  

```Error XPDY0002 in file:///tmp/.mount_softwa2finJs/usr/bin/nx_software_center, at line 1, column 1: The focus is undefined.```  

This causes the application to say "Unable to fetch applications list, please check your internet connection"

**Comment by azubieta** [comment]
This is a known error, produces by a mismatch between the versions of
libssl used in the system were the appimage was built and the one in your
system.
Including this lib in the appimage is not recommended as it may produce
even more issues and also is supposed that almost every distro have it.
The solution is to build the appimage in an older base system but right now
we were unable to find the kde plasma packages for Ubuntu trusty, only
xenial is available.

Would you mind to tell us which system are you using?

**Comment by silvernode** [comment]
## Distribution  Info  

```$ lsb_release -a```
```
LSB Version:    1.0
Distributor ID: VoidLinux
Description:    Void Linux
Release:        rolling
Codename:       void
```

## System Info
```$ uname -rs```
```Linux 4.14.22_2```  

```$ ls /usr/lib |grep libssl.so```
```
libssl.so -> libssl.so.44.0.1  
libssl.so.44 -> libssl.so.44.0.1  
libssl.so.44.0.1
```

## Desktop Environment  

```$ plasmashell --version```
```plasmashell 5.12.0```

**Comment by azubieta** [comment]
Thanks! We are working on this.
We will remove the dependency on kf5 and plasma in order to increase portability and allow builds in older systems.

**Comment by silvernode** [comment]
You're welcome! Yeah Void Linux is never stuff than Ubuntu so that could be a problem.

**Comment by star-buck** [comment]
![screenshot_20180309_101429](https://user-images.githubusercontent.com/840070/37202611-e5a5f6ca-2382-11e8-8f00-14f2a9d1df09.png)

**Comment by star-buck** [comment]
I am still getting this error with the latest appimage release on Netrunner Debain 18.03...

**Comment by azubieta** [comment]
The build platform have been changed from Xenial to Trustu would you mind testing the latest build:
https://github.com/nomad-desktop/nx-software-center/releases/download/continuous/Software_Center-x86_64.AppImage

**Comment by azubieta** [comment]
Tested on [Void Linux](https://repo.voidlinux.eu/live/current/void-live-x86_64-20171007-xfce.iso) and [Neon](https://files.kde.org/neon/images/neon-useredition/current/).
The error is no longer present, so I'm closing the issue.
Feel free to reopen if you found it in another platform.
