### ISSUE TITLE
Remove dependency on plasma Qml components

### ISSUE THREAD

**Issue by azubieta** [nomad-desktop/nx-software-center#34]
Depending on plasma qml components is being a drawback for the portability of our Appimage.
In order to achieve a major compatibility whit older systems we must build the appimage in a very old system. But the latest kde plasma binaries are not available in such systems.

As the usage of those components is limited to the UI and there are native replacements for them we can replace them cleanly.

As drawback we will  lose the chameleonic behavior on plasma based desktops.
@UriHerrera Any toughs on this ?

**Comment by star-buck** [comment]
we cant ship em all in the appimage?

**Comment by azubieta** [comment]
Right now it's done that way. But as we only have the plasma-framework binaries for ubuntu xenial the Appimage works only on systems with libraries versions equal or grater than the ones included in that distro.
http://archive.neon.kde.org/user/ repo is used as binary source.

As an alternative we can try building the plasma-framework by our selves for trusty (or Centos 6, the one recommended at the Appimage wiki).

**Comment by UriHerrera** [comment]
> As an alternative we can try building the plasma-framework by our selves for trusty (or Centos 6, the one recommended at the Appimage wiki).

I'd prefer if we did do this.

**Comment by azubieta** [comment]
Let's do it then!!
