### ISSUE TITLE
Application view

### ISSUE THREAD

**Issue by azubieta** [nomad-desktop/nx-software-center#38]
![Design](https://camo.githubusercontent.com/6078fa1aac9a243dbc70fd22d02ff0d8e8f492dd/68747470733a2f2f692e696d6775722e636f6d2f674379367677552e706e67)

**Comment by azubieta** [comment]
https://transfer.sh/6B5DI/Software_Center-fd30cca-x86_64.AppImage

**Comment by azubieta** [comment]
@UriHerrera @star-buck please test it.
Comments are welcome.

**Comment by UriHerrera** [comment]
I'll check it out
