### ISSUE TITLE
Tasks View UI Improvement

### ISSUE THREAD

**Issue by azubieta** [nomad-desktop/nx-software-center#43]
![screenshot_20180313_200412](https://user-images.githubusercontent.com/1138094/37379566-b38068e0-26f9-11e8-9876-6ec823b939e9.png)
@UriHerrera any thoughts ?

**Comment by azubieta** [comment]
https://transfer.sh/ecvKD/Software_Center-69ac81f-x86_64.AppImage

**Comment by UriHerrera** [comment]
That looks pretty good.

**Comment by azubieta** [comment]
![screenshot_20180314_134911](https://user-images.githubusercontent.com/1138094/37427325-b146aa18-278e-11e8-9333-58dde373ee65.png)
@UriHerrera Any ideas about how to make that counter look awesome ?

**Comment by UriHerrera** [comment]
Make the counter this color: `#EC407A` with a 1px border using  this color: `#D81B60` and the text white (at all times) so it contrasts.

**Comment by azubieta** [comment]
![screenshot_20180314_163118](https://user-images.githubusercontent.com/1138094/37434780-6d81e078-27a6-11e8-9987-e12145264ed8.png)

**Comment by azubieta** [comment]
#14

**Comment by UriHerrera** [comment]
> ![screenshot_20180314_163118](https://user-images.githubusercontent.com/1138094/37434780-6d81e078-27a6-11e8-9987-e12145264ed8.png)

Awesome!.

**Comment by azubieta** [comment]
Merging :smile:
