### ISSUE TITLE
Software Center Issue

### ISSUE THREAD

**Issue by RichardLaya** [nomad-desktop/nx-software-center#49]
Esto es en una instalación nueva, lo único agregado al sistema es un archivo **rtl8723be.conf** en `/etc/modprobe.d/` para aumentar la potencia de señal wifi.
posterior a eso quise actualizar el sistema o instalar paquetes adicionales desde el centro de software y me encontré con esto.
Dejo la salida de la terminal y unas capturas.

```
richardl@nitlap:~$ nx_software_center
Both point size and pixel size set. Using pixel size.
Error FODC0002 in https://www.appimagehub.com/ocs/v1/content/data?package_types=1&page=0: Error transferring https://www.appimagehub.com/ocs/v1/content/data?package_types=1&page=0 - server replied: Forbidden
Error XPDY0002 in file:///usr/bin/nx_software_center, at line 1, column 1: The focus is undefined.
Parser error:  "Download Error"
```

![screenshot_20180410_174015](https://user-images.githubusercontent.com/19170362/38587649-dadcd8de-3ce7-11e8-90a8-a58b805aa602.png)
![screenshot_20180410_175001](https://user-images.githubusercontent.com/19170362/38587650-db03473a-3ce7-11e8-81c8-c681e142ca2e.png)
![screenshot_20180410_175048](https://user-images.githubusercontent.com/19170362/38587651-db2df732-3ce7-11e8-999a-f727e4b76f12.png)

**Comment by rvs75** [comment]
Bug fixed. Works again.

**Comment by RichardLaya** [comment]
Its working right now. Thank u very much.
