### ISSUE TITLE
Support for Appimages

### ISSUE THREAD

**Issue by UriHerrera** [nomad-desktop/nx-software-center#9]
Unlike Snaps, Appimages don't require setting up a store [1], so by supporting this format the software center would just have to keep track of what Appimages are "installed" for instance: Using an XML formatted list. 

Installing/Uninstalling meaning that the user moves files to/out of a common location for example: ~/.local/share/appimages or /usr/share/appimages (note these aren't xdg paths just an example).

In this sense managing Appimages would be like sideloading an APK on an Android device.

1.(We can't set up an "official" Snap store of our own because the server code to create it is proprietary so we have to rely on Ubuntu to provide an official store).

**Comment by star-buck** [comment]
Appimages support would be great.

**Comment by probonopd** [comment]
Check out the `appimaged` daemon which can integrate and remove menu entries, icons, MIME types, etc. 

https://github.com/AppImage/AppImageKit#appimaged-usage

So supporting AppImages would essentially come down to 
* Pre-install `appimaged`, and possibly `Firejail` (for sandboxing) and AppImageUpdate (for binary delta updates)
* Having nx-software-center download them to a location monitored by `appimaged`

> Installing/Uninstalling meaning that the user moves files to/out of a common location for example

The following locations are currently monitored by `appimaged`:
It will register the AppImages in with your system from the following places:
* $HOME/Downloads
* $HOME/.local/bin
* $HOME/bin
* /Applications
* /isodevice/Applications
* /isofrom/Applications
* /run/archiso/img_dev/Applications
* /opt
* /usr/local/bin

**Comment by azubieta** [comment]
Done at 7e45d496422cf66cc612a915b8a6bcac05b03e44
